# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-02T20:02:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class Performance(BaseModel):
    workerMs: int = Field(..., ge=0)
    lookupMs: int = Field(..., ge=0)


class AddressSearchResult(BaseModel):
    udprn: int
    suggestion: str = Field(
        ...,
        description='Single-line typeahead label, e.g. "57 Wimpole Street, London, W1G 8YW".',
    )


class Meta(BaseModel):
    countResults: int = Field(..., ge=0)
    requestId: str
    performance: Performance


class ErrorEnvelope(BaseModel):
    success: Literal[False]
    error: str
    details: str | None = None
    results: list[Any] = Field(..., max_length=0, min_length=0)
    meta: Meta


class Address(BaseModel):
    udprn: int = Field(
        ...,
        description="Unique Delivery Point Reference Number — Royal Mail's per-address ID.",
    )
    postcode: str
    postcode_outward: str | None = None
    postcode_inward: str | None = None
    postcode_type: str | None = None
    address_line_1: str | None = None
    address_line_2: str | None = None
    address_line_3: str | None = None
    post_town: str | None = None
    organisation_name: str | None = None
    department_name: str | None = None
    building_name: str | None = None
    building_number: str | None = None
    sub_building_name: str | None = None
    po_box: str | None = None
    thoroughfare: str | None = None
    dependent_thoroughfare: str | None = None
    dependent_locality: str | None = None
    double_dependent_locality: str | None = None
    delivery_point_suffix: str | None = None
    country: str | None = None
    county: str | None = None
    district: str | None = None
    ward: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    eastings: int | None = None
    northings: int | None = None


class AddressUdprnEnvelope(BaseModel):
    success: Literal[True]
    results: list[Address]
    meta: Meta


class Deliverability(Enum):
    """
    Aggregated verdict.
    """

    deliverable = 'deliverable'
    undeliverable = 'undeliverable'
    risky = 'risky'
    unknown = 'unknown'
    invalid = 'invalid'


class EmailResult(BaseModel):
    email: str
    isValidSyntax: bool
    didYouMean: str | None
    isDisposable: bool
    isFreeProvider: bool
    isRoleAccount: bool
    mxFound: bool
    smtpCheck: str | None
    isCatchAll: bool | None
    deliverability: Deliverability = Field(..., description='Aggregated verdict.')


class PhoneResult(BaseModel):
    number: str
    isValid: bool
    isPossible: bool
    type: str | None
    countryCode: str | None
    countryName: str | None
    nationalFormat: str | None
    internationalFormat: str | None
    e164Format: str | None
    originalCarrier: str | None
    currentCarrier: str | None
    isPorted: bool | None
    isReachable: bool | None
    mcc: str | None
    mnc: str | None
    level: str | None
    lookupError: str | None = None


class MetaConnect(BaseModel):
    requestId: str
    performance: Performance


class ConnectError(BaseModel):
    success: Literal[False]
    error: str
    details: str | None = None
    meta: MetaConnect


class AddressSearchEnvelope(BaseModel):
    success: Literal[True]
    results: list[AddressSearchResult]
    meta: Meta


class AddressPostcodeEnvelope(BaseModel):
    success: Literal[True]
    results: list[Address]
    meta: Meta


class EmailEnvelope(BaseModel):
    success: Literal[True]
    results: list[EmailResult]
    meta: Meta


class PhoneEnvelope(BaseModel):
    success: Literal[True]
    results: list[PhoneResult]
    meta: Meta


class ConnectSuccess(BaseModel):
    success: Literal[True]
    meta: MetaConnect
